sudo: required
services: docker
cache:
  directories: $HOME/.m2
env: officefloor_skip_stress_tests=true officefloor_code_coverage=true
after_success: bash <(curl -s https://codecov.io/bash)
jobs:
  include:
    - name: Java 8
      os: linux
      dist: xenial
      language: java
      jdk: openjdk8
      install: ./.travis-install.sh
      script: ./.travis-script.sh
      addons:
        apt:
          packages: openjfx
    - name: Java 11 (Linux)
      os: linux
      dist: xenial
      language: java
      jdk: openjdk11
      install: ./.travis-install.sh
      script: ./.travis-script.sh
    - name: Java 11 (Windows)
      language: shell
      script:
        - choco install jdk11 -params "source=false"
        - choco install maven
        - ./.travis-script.sh
