sudo: required
services: docker
cache:
  directories: $HOME/.m2
install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install -y maven; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then export "JAVA_HOME=/c/Program Files/Java/jdk1.8.0_211"; fi
  - ./.travis-install.sh
jobs:
  include:
    - name: Java 8 (Linux)
      os: linux
      dist: xenial
      language: java
      jdk: openjdk8
      env: officefloor_skip_stress_tests=true
      addons:
        apt:
          packages: openjfx
    - name: Java 8 (Windows)
      os: windows
      language: shell
      env: officefloor_skip_stress_tests=true officefloor_docker_available=false officefloor_gcloud_available=false
    - name: Java 11 (Linux)
      os: linux
      dist: xenial
      language: java
      jdk: openjdk11
      env: officefloor_skip_stress_tests=true officefloor_code_coverage=true
      script: ./.travis-script.sh
      after_success: bash <(curl -s https://codecov.io/bash)

