sudo: required
services: docker
cache:
  directories: $HOME/.m2
install: ./.travis-install.sh
script: ./.travis-script.sh
jobs:
  include:
    - name: Java 8 (Linux)
      os: linux
      dist: xenial
      language: java
      jdk: openjdk8
      env: officefloor_skip_stress_tests=true
      addons:
        apt:
          packages: openjfx
    - name: Java 8 (Windows)
      os: windows
      language: shell
      env: officefloor_skip_stress_tests=true officefloor_docker_available=false officefloor_gcloud_available=false
      install:
        - choco install -y maven
        - export "JAVA_HOME=/c/Program Files/Java/jdk1.8.0_211"
      script: cd officefloor/bom; mvn -B clean install
    - name: Java 11 (Linux)
      os: linux
      dist: xenial
      language: java
      jdk: openjdk11
      env: officefloor_skip_stress_tests=true officefloor_code_coverage=true
      after_success: bash <(curl -s https://codecov.io/bash)
