dist: xenial
language: java
jdk:
  - openjdk8
  - openjdk11
sudo: required
services: docker
cache:
  directories: $HOME/.m2
env: officefloor_skip_stress_tests=true officefloor_code_coverage=true
before_install: cd officefloor/bom
install: true
script: mvn install -B
after_success: bash <(curl -s https://codecov.io/bash)
after_failure: cat officefloor/maven/woof-archetype/target/test-classes/projects/woof/project/WoofArchetypeResult/target/failsafe-reports/TEST-net.officefloor.test.RunApplicationIT.xml
