sudo: required
services: docker
install: . ./.travis-install.sh
script: ./.travis-script.sh
jobs:
  include:
    - name: Java 8 (Linux)
      os: linux
      dist: xenial
      language: java
      jdk: openjdk8
      env: officefloor_skip_stress_tests=true CUSTOM_MVN_VERSION=3.6.3
      addons:
        apt:
          packages: openjfx
    - name: Java 8 (Windows)
      os: windows
      language: shell
      env: officefloor_skip_stress_tests=true officefloor_docker_available=false officefloor_gcloud_available=false
      install:
        - choco install -y jdk8 -params "source=false" -params 'installdir=c:\\java'
        - export "JAVA_HOME=/c/java"
        - choco install -y maven
        - export MAVEN_OPTS="-Xmx2048m"
      script: cd officefloor/bom; /c/ProgramData/chocolatey/lib/maven/apache-maven-3.6.3/bin/mvn -q -B -e clean install
    - name: Java 11 (Linux)
      os: linux
      dist: xenial
      language: java
      jdk: openjdk11
      env: officefloor_skip_stress_tests=true officefloor_code_coverage=true CUSTOM_MVN_VERSION=3.6.3
      after_success: bash <(curl -s https://codecov.io/bash)
