trigger:
- master

strategy:
  matrix:
    linux_java_8:
      imageName: 'ubuntu-latest'
      javaVersion: '1.8'
    linux_java_11:
      imageName: 'ubuntu-latest'
      javaVersion: '1.11'
#    mac:
#      imageName: 'macos-latest'
#    windows:
#      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

steps:
- task: Maven@3
  displayName: Main
  inputs:
    mavenPomFile: 'officefloor/bom/pom.xml'
    goals: 'install'
    options: '-DskipStress'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: $(javaVersion)
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
