trigger:
- master

strategy:
  matrix:
    java_8:
      imageName: 'windows-latest'
      javaVersion: '1.8'
      isPublishResults: false
    linux:
      imageName: 'ubuntu-latest'
      javaVersion: '1.11'
      isPublishResults: true
#    mac:
#      imageName: 'macos-latest'
#    windows:
#      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

variables:
  isPublishCodeCoverage: $(isPublishResults)
  officefloor_code_coverage: $(isPublishResults)

steps:
- task: Maven@3
  displayName: Main
  inputs:
    mavenPomFile: 'officefloor/bom/pom.xml'
    goals: 'install'
    options: '-DskipStress'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: $(javaVersion)
    jdkArchitectureOption: 'x64'
    publishJUnitResults: $(isPublishResults)
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
- script: |
    bash <(curl -s https://codecov.io/bash)
  displayName: 'Upload Code Coverage'
  condition: eq(variables.isPublishCodeCoverage, true)
