trigger:
- master

strategy:
  matrix:
    java_8:
      imageName: 'ubuntu-latest'
      zuluVersion: 'zulu8.48.0.51-ca-fx-jdk8.0.262-linux_x64'
      zuluHome: '/tmp/$(zuluVersion)'
      javaVersion: '1.8'
      javaHomeOption: 'Path'
      isDockerAvailable: false
      isPublishResults: false
    linux:
      imageName: 'ubuntu-latest'
      javaVersion: '1.11'
      javaHomeOption: 'JDKVersion'
      isDockerAvailable: true
      isPublishResults: true
#    mac:
#      imageName: 'macos-latest'
#    windows:
#      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

variables:
  JDK_VERSION: $(javaVersion)
  OFFICEFLOOR_CODE_COVERAGE: $(isPublishResults)
  OFFICEFLOOR_DOCKER_AVAILABLE: $(isDockerAvailable)

steps:
- script: |
    # Install Zulu JDK 8 (for JavaFx with SWT): https://docs.azul.com/zulu/zuludocs/ZuluUserGuide/InstallingZulu/InstallOnLinuxUsingDebRepository.htm
    # sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 0xB1998361219BD9C9
    # wget https://cdn.azul.com/zulu/bin/zulu-repo_1.0.0-2_all.deb
    # sudo dpkg -i zulu-repo_1.0.0-2_all.deb
    # sudo apt-get update
    # sudo apt-get install zulu8-jdk
    # Install ZuluFx (JavaFx): https://www.azul.com/downloads/zulu-community/?version=java-8-lts&package=jdk-fx
    cd /tmp
    wget https://cdn.azul.com/zulu/bin/$(zuluVersion).tar.gz
    tar -zxf $(zuluVersion).tar.gz
    # Override existing java
    echo "##vso[task.prependpath]$(zuluHome)/bin"
  displayName: 'Install ZuluJDK 8 with JavaFX'
  condition: eq(variables.JDK_VERSION, '1.8')
- task: Maven@3
  displayName: CI
  inputs:
    mavenPomFile: 'officefloor/bom/pom.xml'
    goals: 'install'
    options: '-DskipStress'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: $(javaHomeOption)
    jdkVersionOption: $(javaVersion)
    jdkDirectory: $(zuluHome)
    publishJUnitResults: $(isPublishResults)
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
- script: |
    bash <(curl -s https://codecov.io/bash)
  displayName: 'Upload Code Coverage'
  condition: eq(variables.OFFICEFLOOR_CODE_COVERAGE, true)
- task: Maven@3
  displayName: 'Eclipse 2018-12'
  inputs:
    mavenPomFile: 'officefloor/editor/pom.xml'
    goals: 'clean install'
    options: '-P 2018-12.target'
    javaHomeOption: $(javaHomeOption)
    jdkVersionOption: $(javaVersion)
    jdkDirectory: $(javaHomePath)
    publishJUnitResults: false
- task: Maven@3
  displayName: 'Eclipse PHOTON'
  inputs:
    mavenPomFile: 'officefloor/editor/pom.xml'
    goals: 'clean install'
    options: '-P PHOTON.target'
    javaHomeOption: $(javaHomeOption)
    jdkVersionOption: $(javaVersion)
    jdkDirectory: $(javaHomePath)
    publishJUnitResults: false
- task: Maven@3
  displayName: 'Eclipse OXYGEN'
  inputs:
    mavenPomFile: 'officefloor/editor/pom.xml'
    goals: 'clean install'
    options: '-P OXYGEN.target'
    javaHomeOption: $(javaHomeOption)
    jdkVersionOption: $(javaVersion)
    jdkDirectory: $(javaHomePath)
    publishJUnitResults: false
